server:
  port: 8082

jwt:
  # base64 encoded key
  secret: 9i3Bk8SJ3CfqIm+v9JJjHc5PGmqNmevaXDLYX4k0sW9hmhuvA6rTNWIM6uISlbVWcn28bMs+gY+P3LLzRytHMQ==
  # 30min
  secs_to_expire_access: 1800
  # 30days
  secs_to_expire_refresh: 2592000

oauth2:
  redirect-uris: http://localhost:3000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
            redirect_uri: "{baseUrl}/auth/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            client_id: ${GITHUB_CLIENT_ID}
            client_secret: ${GITHUB_CLIENT_SECRET}
            redirect_uri: "{baseUrl}/auth/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user